name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  HAXE_VERSION: 4.3.4
  APP_VERSION: 4.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm setup
          hmm install
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install actuate --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hxCodec --quiet
          haxelib install hxvlc --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list

      - name: Create Version Tag
        run: echo "${{ env.APP_VERSION }}-${{ github.run_id }}" > VERSION

      - name: Build
        run: |
          haxelib run lime build linux \
            --app-version="${{ env.APP_VERSION }}-${{ github.run_id }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: export/release/linux/bin


  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Install Dependencies
        shell: cmd
        run: |
          haxelib setup C:/haxelib
          haxelib install hmm --quiet
          haxelib run hmm setup
          hmm install
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install actuate --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hxCodec --quiet
          haxelib install hxvlc --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list

      - name: Create Version Tag
        run: echo "${{ env.APP_VERSION }}-${{ github.run_id }}" > VERSION

      - name: Build
        run: |
          haxelib run lime build windows \
            --app-version="${{ env.APP_VERSION }}-${{ github.run_id }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: export/release/windows/bin


  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Install Dependencies
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm setup
          hmm install
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install actuate --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hxCodec --quiet
          haxelib install hxvlc --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list

      - name: Create Version Tag
        run: echo "${{ env.APP_VERSION }}-${{ github.run_id }}" > VERSION

      - name: Build
        run: |
          haxelib run lime build mac \
            --app-version="${{ env.APP_VERSION }}-${{ github.run_id }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: export/release/macos/bin
